CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_CONSTRAINT_ENABLE`()
BEGIN
    
	DECLARE PROCESS_NAME VARCHAR(30);
    DECLARE OPERATION_TYPE VARCHAR(50);
    DECLARE LOG_DETAILS VARCHAR(50);
    
    
    SET OPERATION_TYPE = 'ADDING CONSTRIANT';
    SET PROCESS_NAME = 'SP_CONSTRAINT_ENABLE';
    
    
ALTER TABLE tbl_fnl_category ADD CONSTRAINT PK_CAT_ID PRIMARY KEY (category_id);
ALTER TABLE tbl_fnl_store ADD CONSTRAINT PK_store_ID  PRIMARY KEY (store_id);
ALTER TABLE tbl_fnl_address ADD CONSTRAINT  PK_ADD_ID PRIMARY KEY (address_id);
ALTER TABLE tbl_fnl_film_category ADD CONSTRAINT  PK_FM_ID PRIMARY KEY (film_id);
ALTER TABLE tbl_fnl_film_text ADD CONSTRAINT PK_FM_ID PRIMARY KEY (film_id);
ALTER TABLE tbl_fnl_inventory ADD CONSTRAINT PK_IN_ID PRIMARY KEY (inventory_id);
ALTER TABLE tbl_fnl_customer ADD CONSTRAINT PK_CUST_ID PRIMARY KEY (customer_id);
ALTER TABLE tbl_fnl_city ADD CONSTRAINT PK_IN_ID PRIMARY KEY (inventory_id);
ALTER TABLE tbl_fnl_film ADD CONSTRAINT PK_FIL_ID PRIMARY KEY (film_id);
ALTER TABLE tbl_fnl_payment ADD CONSTRAINT PK_PAY_ID PRIMARY KEY (payment_id);
ALTER TABLE tbl_fnl_language ADD CONSTRAINT PK_LAN_ID PRIMARY KEY (language_id);
ALTER TABLE tbl_fnl_actor ADD CONSTRAINT PK_ACT_ID PRIMARY KEY (actor_id);
ALTER TABLE tbl_fnl_rental ADD CONSTRAINT PK_REN_ID PRIMARY KEY (rental_id);
ALTER TABLE tbl_fnl_staff ADD CONSTRAINT PK_ST_ID PRIMARY KEY (staff_id);
ALTER TABLE tbl_fnl_country ADD CONSTRAINT PK_COU_ID PRIMARY KEY (country_id);

INSERT INTO HRDB_SYS_AUDIT_CONTROL 
    (
    PROCESS_NAME,
    OPERATION_TYPE,
    OPERATED_BY,
	OPERATION_DATE)
    VALUES 
        (
        PROCESS_NAME,
        OPERATION_TYPE,
        CURRENT_USER(),
        CURRENT_TIMESTAMP());
        

END